services:
  webapi:
    build:
      context: ./MenuChooser-API
      dockerfile: Dockerfile
    ports:
      - "7103:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      TokenKey: "o8ZzqyQvpjQ4ze2SSHMV_qRy2qGxJLxZS7Oc3eZAIItR8gwwZ0PC_RCUkz0wgaggcyEmytJEEKczPCeNcu4tXw"
      DatabaseConfiguration__ConnectionString: "mongodb://mongo:27017"
      DatabaseConfiguration__DatabaseName: "MenuChooser"
      DatabaseConfiguration__CollectionsNames__0: "Menu"
      DatabaseConfiguration__CollectionsNames__1: "User"
      DatabaseConfiguration__CollectionsNames__2: "Product"
      DatabaseConfiguration__CollectionsNames__3: "Recipe"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:7
    ports:
      - "27018:27017" # dostęp z zewnątrz np. MongoDB Compass
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
